# Generated by Django 4.2.23 on 2025-07-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='bluetooth_version',
            field=models.CharField(blank=True, help_text='Bluetooth version', max_length=20),
        ),
        migrations.AddField(
            model_name='hardware',
            name='dimensions',
            field=models.CharField(blank=True, help_text='W x D x H in mm or inches', max_length=100),
        ),
        migrations.AddField(
            model_name='hardware',
            name='display_specs',
            field=models.CharField(blank=True, help_text='Display: Resolution, Size, Panel Type', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='eol_date',
            field=models.DateField(blank=True, help_text='End of Life date', null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='ethernet_ports',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Ethernet ports', null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('atx', 'ATX'), ('micro_atx', 'Micro-ATX'), ('mini_itx', 'Mini-ITX'), ('e_atx', 'E-ATX'), ('1u', '1U Rack'), ('2u', '2U Rack'), ('4u', '4U Rack'), ('tower', 'Tower'), ('desktop', 'Desktop'), ('all_in_one', 'All-in-One'), ('external', 'External'), ('pcie', 'PCIe Card'), ('m2', 'M.2'), ('2_5_inch', '2.5 inch'), ('3_5_inch', '3.5 inch')], max_length=20),
        ),
        migrations.AddField(
            model_name='hardware',
            name='interface',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('usb_2', 'USB 2.0'), ('usb_3', 'USB 3.0/3.1'), ('usb_c', 'USB-C'), ('thunderbolt', 'Thunderbolt'), ('ethernet', 'Ethernet RJ45'), ('wifi', 'WiFi'), ('bluetooth', 'Bluetooth'), ('hdmi', 'HDMI'), ('displayport', 'DisplayPort'), ('vga', 'VGA'), ('dvi', 'DVI'), ('sata', 'SATA'), ('nvme', 'NVMe'), ('pcie', 'PCIe'), ('sas', 'SAS'), ('fiber', 'Fiber Optic')], max_length=20),
        ),
        migrations.AddField(
            model_name='hardware',
            name='memory_specs',
            field=models.CharField(blank=True, help_text='RAM: Capacity, Type, Speed', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='network_specs',
            field=models.CharField(blank=True, help_text='Network: Ports, Speed, Standards', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='operating_temp',
            field=models.CharField(blank=True, help_text='Operating temperature range', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='part_number',
            field=models.CharField(blank=True, help_text='Manufacturer part number', max_length=100),
        ),
        migrations.AddField(
            model_name='hardware',
            name='power_specs',
            field=models.CharField(blank=True, help_text='Power: Wattage, Efficiency, Voltage', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='processor_specs',
            field=models.CharField(blank=True, help_text='CPU: Cores, Clock Speed, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='replacement_model',
            field=models.ForeignKey(blank=True, help_text='Suggested replacement model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.hardware'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='sku',
            field=models.CharField(blank=True, help_text='Internal SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='hardware',
            name='storage_specs',
            field=models.CharField(blank=True, help_text='Storage: Capacity, Type, Speed', max_length=200),
        ),
        migrations.AddField(
            model_name='hardware',
            name='support_level',
            field=models.CharField(blank=True, help_text='Support level included', max_length=100),
        ),
        migrations.AddField(
            model_name='hardware',
            name='usb_ports',
            field=models.PositiveIntegerField(blank=True, help_text='Number of USB ports', null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='warranty_period',
            field=models.CharField(blank=True, help_text='Warranty period (e.g., 3 years)', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight in kg or lbs', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='wifi_standard',
            field=models.CharField(blank=True, help_text='WiFi standard (e.g., 802.11ax)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('server', 'Server'), ('storage', 'Storage'), ('network', 'Networking'), ('security', 'Security'), ('desktop', 'Desktop/Laptop'), ('peripheral', 'Peripheral'), ('software', 'Software License'), ('mainboard', 'Mainboard/Motherboard'), ('cpu', 'CPU/Processor'), ('ram', 'RAM/Memory'), ('ssd', 'SSD/Storage Drive'), ('hdd', 'HDD/Hard Drive'), ('gpu', 'GPU/Graphics Card'), ('psu', 'Power Supply Unit'), ('cooling', 'Cooling System'), ('case', 'Computer Case'), ('monitor', 'Monitor/Display'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer/Scanner'), ('ups', 'UPS/Power Backup'), ('cable', 'Cables/Connectors'), ('router', 'Router/Gateway'), ('switch', 'Network Switch'), ('wifi', 'WiFi Equipment'), ('firewall', 'Firewall/Security'), ('other', 'Other')], max_length=20),
        ),
    ]
