# Generated by Django 4.2.23 on 2025-07-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0002_hardware_bluetooth_version_hardware_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='final_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='financial_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='financial_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='general_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_supervisor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='technical_feasibility_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='technical_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerQuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(help_text='Detailed project requirements and specifications')),
                ('wishlist_items', models.TextField(help_text="Customer's wishlist of components or services")),
                ('budget_range', models.CharField(blank=True, help_text="Customer's budget expectation", max_length=100)),
                ('expected_delivery_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('converted', 'Converted to Quotation'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_notes', models.TextField(blank=True, help_text='Internal notes from sales team')),
                ('assigned_sales_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('converted_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.quotation')),
                ('existing_customer', models.ForeignKey(blank=True, help_text='Link to existing customer if found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.customer')),
            ],
            options={
                'verbose_name': 'Customer Quotation Request',
                'verbose_name_plural': 'Customer Quotation Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='original_request',
            field=models.ForeignKey(blank=True, help_text='Original customer request that generated this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.customerquotationrequest'),
        ),
    ]
