# Generated by Django 4.2.23 on 2025-07-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_final_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Address for billing'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Address for delivery'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_address',
            field=models.TextField(blank=True, help_text='Address for installation'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('server', 'Server'), ('storage', 'Storage'), ('network', 'Networking'), ('security', 'Security'), ('desktop', 'Desktop/Laptop'), ('peripheral', 'Peripheral'), ('software', 'Software License'), ('mainboard', 'Mainboard/Motherboard'), ('cpu', 'CPU/Processor'), ('ram', 'RAM/Memory'), ('internal_storage', 'Internal Storage'), ('gpu', 'GPU/Graphics Card'), ('connectivity', 'Connectivity Component'), ('ssd', 'SSD/Storage Drive'), ('hdd', 'HDD/Hard Drive'), ('psu', 'Power Supply Unit'), ('cooling', 'Cooling System'), ('case', 'Computer Case'), ('monitor', 'Monitor/Display'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer/Scanner'), ('ups', 'UPS/Power Backup'), ('cable', 'Cables/Connectors'), ('router', 'Router/Gateway'), ('switch', 'Network Switch'), ('wifi', 'WiFi Equipment'), ('firewall', 'Firewall/Security'), ('other', 'Other')], max_length=20),
        ),
    ]
