# Generated by Django 4.2.23 on 2025-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_customerquotationrequest_request_number_and_more'),
    ]

    operations = [
        # Add new approval fields
        migrations.AddField(
            model_name='quotation',
            name='sales_staff_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_staff_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_manager_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
