# Generated by Django 4.2.5 on 2025-07-23 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0005_auto_20250723_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('os_setup', 'Device OS Setup & Apps Installation'), ('onsite_install', 'Onsite Installation & Configuration'), ('onsite_training', 'Onsite Training'), ('onsite_maintenance', 'Onsite Maintenance'), ('remote_support', 'Remote Support'), ('consulting', 'Technical Consulting'), ('project_mgmt', 'Project Management'), ('other', 'Other Personnel Services')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of this personnel cost category')),
                ('standard_hourly_rate', models.DecimalField(decimal_places=2, help_text='Standard hourly rate for this category', max_digits=8)),
                ('skill_level_required', models.CharField(blank=True, help_text='Required skill level (Junior, Senior, Expert)', max_length=50)),
                ('estimated_hours_range', models.CharField(blank=True, help_text='Typical hours range (e.g., 4-8 hours)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personnel Cost Category',
                'verbose_name_plural': 'Personnel Cost Categories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationPersonnelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Hours estimated by technical manager', max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for this specific task', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('description', models.TextField(help_text='Detailed description of work required')),
                ('complexity_notes', models.TextField(blank=True, help_text='Notes about complexity factors affecting estimation')),
                ('risk_factors', models.TextField(blank=True, help_text='Potential risks that could affect cost/time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Finance'), ('approved', 'Approved by Finance'), ('rejected', 'Rejected by Finance'), ('revised', 'Needs Revision')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, help_text="Finance manager's review comments")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.personnelcostcategory')),
                ('estimated_by', models.ForeignKey(help_text='Technical manager who provided the estimation', on_delete=django.db.models.deletion.CASCADE, related_name='estimated_personnel_costs', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_costs', to='quotations.quotation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Finance manager who reviewed this cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_personnel_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel Cost Estimation',
                'verbose_name_plural': 'Personnel Cost Estimations',
                'ordering': ['quotation', 'cost_category'],
            },
        ),
        migrations.CreateModel(
            name='MarginAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hardware_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_personnel_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('gross_margin', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('margin_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('project_risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=10)),
                ('technical_risk_notes', models.TextField(blank=True, help_text='Technical risks that could affect costs')),
                ('market_risk_notes', models.TextField(blank=True, help_text='Market/competitive risks')),
                ('operational_risk_notes', models.TextField(blank=True, help_text='Operational risks (resources, timeline)')),
                ('sustainability_assessment', models.CharField(blank=True, choices=[('sustainable', 'Sustainable'), ('marginal', 'Marginal'), ('unsustainable', 'Unsustainable')], help_text='Overall sustainability assessment', max_length=15)),
                ('finance_comments', models.TextField(blank=True, help_text="Finance manager's detailed comments")),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improving margin')),
                ('estimated_competitor_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated competitor pricing', max_digits=12, null=True)),
                ('price_competitiveness', models.TextField(blank=True, help_text='Analysis of price competitiveness')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_analyses', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margin_analysis', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Margin Analysis',
                'verbose_name_plural': 'Margin Analyses',
            },
        ),
        migrations.CreateModel(
            name='HardwareCostImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(help_text='CSV file with hardware costs', upload_to='hardware_costs/')),
                ('description', models.TextField(blank=True, help_text='Description of this import')),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('errors_log', models.TextField(blank=True, help_text='Import errors and warnings')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this import is currently active')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hardware Cost Import',
                'verbose_name_plural': 'Hardware Cost Imports',
                'ordering': ['-import_date'],
            },
        ),
    ]
